version: '3.8'

services:

  archivy:
    image: harshavardhanj/archivy:0.1.0
    ports:
      - "5000:5000"
    volumes:
      - archivyData:/archivy/data
    cap_drop:
      - ALL

volumes:
  archivyData:
