site_name: Archivy
theme:
  name: material
  logo: img/logo-2.png
  favicon: img/logo-2.png
  features:
    - navigation.tabs
  custom_dir: docs/overrides


plugins:
  - mkdocstrings
  - search


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
  - footnotes

nav:
  - Home: 
    - "index.md"
    - What makes Archivy different: "difference.md"
    - Architecture: "reference/architecture.md"
    - Contributing: "CONTRIBUTING.md"
  - Getting Started:
      - Installing Archivy: "install.md"
      - Usage: "usage.md"
      - Search: "setup-search.md"
      - Config: "config.md"
      - Editing: "editing.md"
      - What's Next: "whats_next.md"
  - Plugins:
      - Index: "plugins.md"
  - API Reference:
    - Architecture: "reference/architecture.md"
    - Web API: "reference/web_api.md"
    - Models for User and DataObj: "reference/models.md"
    - Dataobj Filesystem Layer: "reference/filesystem_layer.md"
    - Helpers: "reference/helpers.md"
    - Hooks: "reference/hooks.md"
    - Search: "reference/search.md" 
    - Web Inputs For Plugins: "reference/web_inputs.md"

repo_url: https://github.com/archivy/archivy
repo_name: archivy
